### ISSUE TITLE
Missing git tag for 2023.4.20 release

### ISSUE THREAD

**Issue by felixonmars** [pypa/trove-classifiers#139]
It would be nice to keep PyPI releases and git tags in sync :)

**Comment by di** [comment]
Not sure what happened, looks like the workflow failed: https://github.com/pypa/trove-classifiers/actions/runs/4756142228/jobs/8451274834

I created the release/tag manually: https://github.com/pypa/trove-classifiers/releases/tag/2023.4.20

Will leave this open to see if it happens again, but this might be a transient failure since nothing has really changed here to cause this as far as I'm aware.
