### ISSUE TITLE
Add missing SPDX ID and OSI name

### ISSUE THREAD

**Issue by perillo** [pypa/trove-classifiers#165]
Some licenses are missing the SPDX ID, thus making the actual license uncertain.

As an example, in https://pypi.org/project/undatum/ the license is "OSI Approved :: BSD License" but pypi reports "BSD License (MIT)".
The actual license file reports MIT, so this is certain an issued caused by the author.

I suggest to add at least the OSI license name and SPDX ID for the popular/strong community licenses: https://opensource.org/licenses/?categories=popular-strong-community.

Thanks.

See also #70

**Comment by di** [comment]
The reason the `undatum` license is rendered like that is because they set both the [`License: MIT` metadata field](https://inspector.pypi.io/project/undatum/1.0.14/packages/d9/43/5d81751be7bfb937bb22032610f1d70739d860fc5f463051fe5fbe58cca1/undatum-1.0.14.tar.gz/undatum-1.0.14/PKG-INFO#line.9) and the [`OSI Approved :: BSD License` classifier](https://inspector.pypi.io/project/undatum/1.0.14/packages/d9/43/5d81751be7bfb937bb22032610f1d70739d860fc5f463051fe5fbe58cca1/undatum-1.0.14.tar.gz/undatum-1.0.14/PKG-INFO#line.19). PyPI is making a best effort to display both things the user has provided.

I think we can probably close this as a duplicate of #17 because it covers updating the license classifiers to make them more accurate.

**Comment by perillo** [comment]
@di I agree. Thanks and sorry for not having noted #17.
