### ISSUE TITLE
Request to add new trove classifier Framework :: Hatch

### ISSUE THREAD

**Issue by ofek** [pypa/trove-classifiers#89]
Request to add a new Trove classifier.

## The name of the classifier(s) you would like to add:

* `Framework :: Hatch`

## Why do you want to add this classifier?

[Hatch](https://github.com/ofek/hatch) is an extensible Python project manager mentioned multiple times on https://packaging.python.org (see [1](https://packaging.python.org/en/latest/key_projects/#hatch), [2](https://packaging.python.org/en/latest/specifications/pypirc/#common-configurations), [3](https://packaging.python.org/en/latest/tutorials/managing-dependencies/#other-tools-for-application-dependency-management), [4](https://packaging.python.org/en/latest/tutorials/packaging-projects/#next-steps)) that has recently undergone a rewrite.

In v1.0.0 releasing in the coming weeks, every major feature is now implemented as a plugin similar to [pytest, tox, and devpi](https://pluggy.readthedocs.io/en/stable/#more-real-world-examples). Comprehensive documentation is located here: https://ofek.dev/hatch/latest/plugins/about/

Two plugins currently exist:

* [hatch-mypyc](https://github.com/ofek/hatch-mypyc) - build hook plugin to first compile all code with [Mypyc](https://github.com/mypyc/mypyc)
* [hatch-containers](https://github.com/ofek/hatch-containers) - plugin to run environments inside Docker containers

It would be nice if the docs for v1 can mention `Framework :: Hatch`

**Comment by pradyunsg** [comment]
Hi! Thanks for the request. Because removing classifiers is very difficult, and the longer the classifier list gets the harder it is to browse, the bar to add new ones is relatively high. Currently, PyPI moderators primarily examine two guidelines for Framework classifiers:

- New Framework classifiers should be created if they are "notable" and
- They will be of immediate use to existing projects (in other words, no creating classifiers simply in anticipation of future uses)

We understand that "notability" is subjective and we'd appreciate help judging that.

As to the other guideline ('immediate use to existing projects'), the best way we've found to demonstrate that is to have 10 or more other project maintainers submit comments on the requesting issue about their desire to use the classifier. Is that something you could assist with?

**Comment by ofek** [comment]
Respectful _bump_ 🙂
